[project]
name = "pyrocketcraft"
version = "1"

dependencies = [
    "numpy>=1.21.2",
    "scipy>=1.5.2",
    "gym~=0.29.0",
    "pybullet==3.2.6",
    "torch>=2.1.2",
    "stable-baselines3[extra]==2.2.1",
]

[tool.setuptools]
packages = ["src"]
